id: PA08ABA8A
initial_creation_type: input
source_metadata:
  title: Nubpa Rigdzin Drak
  language: en
  description: 'Texts by Nubpa Rigdzin Drak (nub pa rig ''dzin grags), who was born
    in the thirteenth century:'
  volume:
    7a16de881e624fd0af546f95bd61edf6:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: null
created_at: '2022-03-01T01:02:54.163885'
last_modified_at: '2022-03-01T01:02:54.163891'
